name: Drata Nikto Vuln Scans
on:
    workflow_dispatch:
jobs:
  red-team-tools:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Subfinder
        run: docker run -v ${{ github.workspace }}:/data projectdiscovery/subfinder:latest -silent -d drata.com -o /data/subs.txt
      - name: Httpx
        run: cat ${{ github.workspace }}/subs.txt | docker run -v ${{ github.workspace }}:/data -i projectdiscovery/httpx -o /data/httpx.txt
      - name: contents of httpx file
        run: cat httpx.txt
      - name: Set permissions
        run: sudo chmod 700 /data/
      - name: Nikto Scans
        run: |
          while read -r line
          do
            # Sanitize URL to be a valid file name (limiting to first 50 characters)
            file_name=$(echo $line | sed 's/[^a-zA-Z0-9]/_/g' | cut -c 1-50)
            docker run --rm -v ${{ github.workspace }}:/data alpine/nikto -h $line -o /data/nikto_${file_name}.json
          done < httpx.txt
      - name: Convert to SARIF
        run: python convert_to_sarif.py
      - name: Upload SARIF files
        run: |
          for file in ${{ github.workspace }}/*.sarif
          do
            echo "Uploading $file"
            echo "::set-env name=SARIF_FILE::$file"
          done
        env:
          SARIF_FILE: ${{ env.SARIF_FILE }}
      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v2.2.1
        env:
          SLACK_COLOR: green
          SLACK_ICON: https://vignette3.wikia.nocookie.net/rvb/images/7/77/Red_Team_Jersey.jpg
          SLACK_MESSAGE: ${{ steps.add_results.outputs.results }}
          SLACK_TITLE: Nuclei Scan Results
          SLACK_FOOTER: Powered by - FalconCore
          SLACK_USERNAME: red-team
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
